version: '3'
services:
  golang:
    environment:
      MIRROR_SOURCE: tencent
    image: hopher/golang:1.12
    container_name: my_golang
    build:
      context: .
      dockerfile: ./services/go/Dockerfile    
    ports:
      - "1313:1313"
    volumes:
      - src:/go/src:rw
      - ./services/go/bin:/go/bin:rw
      - ./services/go/pkg:/go/pkg:rw
    stdin_open: true
    tty: true
    restart: always
  php:
    environment:
      MIRROR_SOURCE: tencent
    image: hopher/php:7.2-fpm
    container_name: my_php
    build:
      context: .
      dockerfile: ./services/php/Dockerfile
    ports:
      - "9501:9501"
      - "9502:9502"
      - "9503:9503"
    volumes:
      - src:/var/www/html:rw
      - ./services/php/etc:/usr/local/etc:ro
    restart: always
    command: php-fpm

  mysql:
    environment:
      MIRROR_SOURCE: tencent    
    image: hopher/mysql:5.7
    container_name: my_mysql
    build:
      context: .
      dockerfile: ./services/mysql/Dockerfile    
    ports:
      - "3306:3306"
    volumes:
      - ./services/mysql/data:/var/lib/mysql:rw
      - ./services/mysql/etc:/etc/mysql:ro # 自定义配置文件
      - ./services/mysql/log:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    command: "--character-set-server=utf8"

  nginx:
    environment:
      MIRROR_SOURCE: tencent    
    image: hopher/nginx:1.15
    container_name: my_nginx
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile     
    depends_on:
      - php
    links:  # links 为 services name, 官方已废弃这个参数
      - php:php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - src:/usr/share/nginx/html:rw
      - ./services/nginx/etc/conf.d:/etc/nginx/conf.d
      - ./services/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    command: nginx -g 'daemon off;'

  redis:
    environment:
      MIRROR_SOURCE: tencent    
    image: hopher/redis:3.2
    container_name: my_redis
    build:
      context: .
      dockerfile: ./services/redis/Dockerfile        
    ports:
      - "6379:6379"
    restart: always
#    
# see: 
#   - https://docs.docker.com/engine/reference/commandline/volume_create/#driver-specific-options
#   - https://github.com/docker/compose/issues/2957
# 
# 相当于: mount -t none -o bind source_path dest_path
volumes:
  src:
    driver: local
    driver_opts:
      device: ${HOME}/src # docker 不支持相对路径
      o: bind